# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef1c5f1c397aec0daf8d440b48e43a4f"
name = "instant-ts-sections"
application_url = "https://instan-ts-section.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_themes,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://instan-ts-section.onrender.com/auth" ]
